primaryIdentifier = /Antibody/text()
summary = /Antibody/Summary/Text/text()
publicName = /Antibody/Public_name/Txt/text()
clonality = /Antibody/Isolation/Clonality/Polyclonal/text()
antigen.primaryIdentifier = /Antibody/Isolation/Antigen/Protein/text()
