primaryIdentifier = /Feature/text()
chromosome = /Feature/Sequence_details/Source_location/Int/Sequence/text()
start = /Feature/Sequence_details/Source_location/Int/Sequence/Int[1]/text()
end = /Feature/Sequence_details/Source_location/Int/Sequence/Int[1]/Int[1]/text()
description = /Feature/Visible/Description/Text/text()
sequenceOntologyTerm.primaryIdentifier = /Feature/Visible/SO_term/SO_term/text()
organism.name = /Feature/Origin/Species/Species/text()
