primaryIdentifier = /Homology_group/text()
title = /Homology_group/Title/Text/text()
type = /Homology_group/Group_type/*/name()
genes.primaryIdentifier = /Homology_group/Member/Gene/text()
proteins.primaryIdentifier = /Homology_group/Member/Protein/text()
