primaryIdentifier = /Person/text()
firstName = /Person/Name/First_name/Txt/text()
lastName = /Person/Name/Last_name/Person_name/text()
full_name = /Person/Name/Full_name/Person_name/text()
email = /Person/Address/Email/Txt/text()
laboratory.primaryIdentifier = /Person/Laboratory/Laboratory/text()
