primaryIdentifier = /Paper/text()
title = /Paper/Reference/Title/Text/text()
journal = /Paper/Reference/Journal/Text/text()
volume = /Paper/Reference/Volume/Txt/text()
pages = /Paper/Reference/Page/Txt/text()
year = /Paper/Reference/Publication_date/Text/text()
firstAuthor = /Paper/Author/Author[1]/text()
