primaryIdentifier = /Rearrangement/text()
type = /Rearrangement/Type/*/name()
description = /Rearrangement/Remark/Text/text()
strains.primaryIdentifier = /Rearrangement/Strain/Strain/text()
genes.primaryIdentifier = /Rearrangement/Positive/Gene_inside/Gene/text()
variation.primaryIdentifier = /Rearrangement/Variation/Variation/text()
