name = /SO_term/SO_name/Text/text()
primaryIdentifier = /SO_term/text()
definition = /SO_term/SO_definition/Text/text()
synonym = /SO_term/SO_synonym//Text[1]/text()
parent = /SO_term/Parent/Is_a/SO_term/
child = /SO_term/Child/Is//SO_term[1]/
			
			
			
			
			
