primaryIdentifier           = /Variation/text()
symbol                      = /Variation/Name/Public_name/Variation_name/text()
otherName                   = /Variation/Name/Other_name/Variation_name/text()

(engineeredAllele)type      = /Variation/Variation_type/Engineered_allele/text()
(allele)type                = /Variation/Variation_type/Allele/text()
(snp)type                   = /Variation/Variation_type/SNP/text()
(naturalVariant)type        = /Variation/Variation_type/Natural_variant/text()

(substitution)typeOfMutation              = /Variation/Sequence_details/Type_of_mutation/Substitution/text()
(deletion)typeOfMutation              = /Variation/Sequence_details/Type_of_mutation/Deletion/text()
(insertion)typeOfMutation              = /Variation/Sequence_details/Type_of_mutation/Insertion/text()

linkedTo                    = /Variation/Linked_to/Variation/text()
species                     = /Variation/Origin/Species/Species/text()

(CRISPR_Cas9)productionMethod = /Variation/Origin/Production_method/CRISPR_Cas9/text()

if.KOConsortiumAllele       = /Variation/Origin/KO_consortium_allele[1]
if.NBPAllele                = /Variation/Origin/NBP_allele[1]

detectionMethod             = /Variation/Origin/Detection_method/Txt/text()

(live)status            = /Variation/Origin/Status/Live/text()

gene.primaryIdentifier      = /Variation/Affects/Gene/Gene/text()
mutagen                     = /Variation/Isolation/Mutagen/Txt/text()
geneClass                   = /Variation/Genetics/Gene_class/Gene_class/text()

opal_UGA                    = /Variation/Affects/Predicted_CDS/CDS/Nonsense/Opal_UGA/Txt/text()
amber_UAG                   = /Variation/Affects/Predicted_CDS/CDS/Nonsense/Amber_UAG/Txt/text()
ochre_UAA                   = /Variation/Affects/Predicted_CDS/CDS/Nonsense/Ochre_UAA/Txt/text()

missenseChange              = /Variation/Affects/Predicted_CDS/CDS/Missense/Int/Txt/text()

phenotype.primaryIdentifier = /Variation/Description/Phenotype/Phenotype/text()
phenotypeNotObserved.primaryIdentifier = /Variation/Description/Phenotype_not_observed/Phenotype/text()
publications.primaryIdentifier = /Variation/Evidence/Paper_evidence/Paper/text()
rearrangements.primaryIdentifier = /Variation/Genetics/Rearrangement/text()
