This file specifies the how to access local postgres databases used for
# building and running and InterMine.bio warehouse.  Also some configuration
# of InterMine behaviour.


#######################
# database properties #
#######################

# if true will log details about execution time of every query
os.production.verboseQueryLog=true

# Access to the postgres database to build into and access from the webapp
db.production.datasource.serverName=localhost
db.production.datasource.databaseName=intermine_prod_5_287_2
db.production.datasource.user=
db.production.datasource.password=

# Temporary database used during the build process, this is re-built
# as sources are loaded and can be discarded once the warehouse build is complete
# It uses the InterMine 'items' metadata format to describe objects.

# common target items database
db.common-tgt-items.datasource.serverName=localhost
db.common-tgt-items.datasource.databaseName=items-intermine
db.common-tgt-items.datasource.user=
db.common-tgt-items.datasource.password=


# userprofile database - used by the webapp to store logins, query history,
# saved bags, templates and tags.
#db.userprofile-production.datasource.serverName=rdbms.wormbase.org
#db.userprofile-production.datasource.port=5432
#db.userprofile-production.datasource.databaseName=userprofile-intermine-dev
#db.userprofile-production.datasource.user=
#db.userprofile-production.datasource.password=

db.userprofile-production.datasource.serverName=localhost
db.userprofile-production.datasource.port=5432
#db.userprofile-production.datasource.databaseName=userprofile-intermine
db.userprofile-production.datasource.databaseName=userprofile_prod
db.userprofile-production.datasource.user=
db.userprofile-production.datasource.password=

resolver.file.rootpath=/mnt/data2/intermine_dev2/datadir/idresolver
dataLoader.allowMultipleErrors=True

#####################
# webapp properties #
#####################

# Web application deployment properties

# location of tomcat server and path of webapp - e.g. access http://localhost:8080/wormmine
webapp.deploy.url=http://localhost:8080
webapp.path=tools/wormmine
#webapp.path=wormmine
webapp.tomcat.version=7

# tomcat username and password needed to deploy webapp
webapp.manager=
webapp.password=

# 'Home' link
webapp.baseurl=http://intermine.wormbase.org
webapp.wormbase.url=https://www.wormbase.org

# account name for superuser (who can edit appearance and publish templates)
superuser.account=staff@wormbase.org
superuser.initialPassword=

# run with no associated web site
project.standalone=true

# details for sending login e-mails
mail.host=localhost
mail.from=help@wormbase.org
mail.subject=Welcome to WormMine
mail.text=You have successfully created an account on WormMine

# text that appears in the header and elsewhere
project.title=WormMine
project.subTitle= Intermine data mining platform for C. elegans and related nematodes
project.releaseVersion=287

# various URLs use this as the prefix
project.sitePrefix=http://intermine.wormbase.org
project.helpLocation=http://www.wormbase.org/tools/support

# recipient of feedback form located on bottom of every page
feedback.destination = help@wormbase.org

# disable openid
openid.allowed=false

# Google oauth2 
oauth2.providers =GOOGLE
oauth2.GOOGLE.client-id =1008804152566-amol0rtpgl9n9ngknqm47ubjmrusfp28.apps.googleusercontent.com
oauth2.GOOGLE.client-secret=8iVIMpGKcQYdOYzzUL-YYTf6
oauth2.GOOGLE.scopes = openid email
oauth2.GOOGLE.id-key = sub
oauth2.GOOGLE.identity-resource = https://www.googleapis.com/plus/v1/people/me/openIdConnect
oauth2.GOOGLE.url.auth=https://accounts.google.com/o/oauth2/auth
oauth2.GOOGLE.url.token=https://www.googleapis.com/oauth2/v3/token
oauth2.GOOGLE.messageformat=BODY
oauth2.GOOGLE.responsetype = JSON
oauth2.GOOGLE.resource-auth-mechanism = header

defaultValues=C. elegans
