[tool.poetry]
name = "post_processing"
version = "0.1.0"
description = ""
authors = ["nuin <nuin@genedrift.org>"]

[tool.poetry.dependencies]
python = "^3.7"
sqlalchemy = "^2.0.16"
intermine = "^1.13.0"
psycopg2-binary = "^2.9.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
